### ISSUE TITLE
Please see email from me

### ISSUE THREAD

**Issue by turian** [SeungHeonDoh/Hear_NT#1]
Hi @SeungHeonDoh et al. Please see the email from me. The email address I have in my Google Form does not work. If you did not receive an email, please comment here or email me directly at lastname@gmail.com

Thanks!

**Comment by seungheondoh** [comment]
Hi Joseph (@turian), 

I'm so sorry for the late reply. I just found the message from the issue in our submitted repo (https://github.com/SeungHeonDoh/Hear_NT/issues/1)
Regarding the submitted model, we are currently double-checking it, please contact us if you have any problems.

Here is my primary mail: seungheondoh@kaist.ac.kr
